[package]
name = "discv5-cli"
version = "0.1.0"
description = "Simple utility to test discv5"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"
readme = "./README.md"
keywords = ["ethereum", "discv5", "discovery", "p2p" ]
repository = "https://github.com/AgeManning/enr-cli"
categories = ["cryptography::cryptocurrencies"]
license = "MIT"
exclude = [
	".gitignore",
	".github/*"
]

[dependencies]
discv5 = "0.1.0-alpha"
clap = "2.33.0"
futures = "0.3.4"
tokio = { version = "0.2.19", features = ["full"] }
libsecp256k1 = "0.3.5"
