[package]
name = "discv5-cli"
version = "0.1.2"
description = "Simple utility to test discv5"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"
readme = "./README.md"
keywords = ["ethereum", "discv5", "discovery", "p2p" ]
repository = "https://github.com/AgeManning/enr-cli"
categories = ["cryptography::cryptocurrencies"]
license = "MIT"
exclude = [
	".gitignore",
	".github/*"
]

[dependencies]
discv5 = { version = "0.1.0-alpha.7", features = ["libp2p"] }
clap = "=3.0.0-beta.1"
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["full"] }
libsecp256k1 = "0.3.5"
sha2 = "0.8.1"
hex = "0.4.2"
simple_logger = "1.6.0"
log = "0.4.8"
libp2p-core = "0.20.1"
